# docker compose notification app
services:
  notification:
    container_name: notification-go
    build: .
    ports:
      - "${NOTIFICATION}:8080"
    volumes:
      - .:/app
    command: go run main.go
    restart: always
    networks:
      - cisbaf_network_apps

networks:
  cisbaf_network_apps:
    external: true
